// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiu0YghQFq0RX8-l9Ovdowtow1hOHWz8g',
    appId: '1:253467975445:web:c296479183e6b7c22a131c',
    messagingSenderId: '253467975445',
    projectId: 'chat-app-724b2',
    authDomain: 'chat-app-724b2.firebaseapp.com',
    storageBucket: 'chat-app-724b2.appspot.com',
    measurementId: 'G-QVRX3SGYKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY1Ws5oShk_LAftXkIguC_q1jJw2qO-xI',
    appId: '1:253467975445:android:b3dfc9fc16a5359b2a131c',
    messagingSenderId: '253467975445',
    projectId: 'chat-app-724b2',
    storageBucket: 'chat-app-724b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLdRPFmKDbjW0jrj3EXIgP__D1A-pdtgc',
    appId: '1:253467975445:ios:1d8b69119d1c6ff12a131c',
    messagingSenderId: '253467975445',
    projectId: 'chat-app-724b2',
    storageBucket: 'chat-app-724b2.appspot.com',
    iosClientId: '253467975445-58tsp4r58nt78rfbirtcng0pqqlsgmfu.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLdRPFmKDbjW0jrj3EXIgP__D1A-pdtgc',
    appId: '1:253467975445:ios:53b22c7efb4b698d2a131c',
    messagingSenderId: '253467975445',
    projectId: 'chat-app-724b2',
    storageBucket: 'chat-app-724b2.appspot.com',
    iosClientId: '253467975445-2hlhdm7todfe6tgv0kmrih0vbv5711bd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
